import java.util.List;

/**
 * Generated by JSON to Code Companion from a JSON sample.
 * Do not hand-edit; regenerate instead.
 */
public class Order {
     private String orderId;
     private int customerId;
     private long totalCents;
     private double totalAmount;
     private boolean isPaid;
     private Object couponCode; // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
     private ShippingAddress shippingAddress;
     private List<String> tags;
     private List<LineItem> lineItems;
     private List<Object> notifications; // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
     private List<Object> mixedShapeArray; // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
     private String firstName;
     private String lastName;

     public String getOrderId() { return orderId; }
     public void setOrderId(String orderId) { this.orderId = orderId; }

     public int getCustomerId() { return customerId; }
     public void setCustomerId(int customerId) { this.customerId = customerId; }

     public long getTotalCents() { return totalCents; }
     public void setTotalCents(long totalCents) { this.totalCents = totalCents; }

     public double getTotalAmount() { return totalAmount; }
     public void setTotalAmount(double totalAmount) { this.totalAmount = totalAmount; }

     public boolean getIsPaid() { return isPaid; }
     public void setIsPaid(boolean isPaid) { this.isPaid = isPaid; }

     public Object getCouponCode() { return couponCode; }
     public void setCouponCode(Object couponCode) { this.couponCode = couponCode; }

     public ShippingAddress getShippingAddress() { return shippingAddress; }
     public void setShippingAddress(ShippingAddress shippingAddress) { this.shippingAddress = shippingAddress; }

     public List<String> getTags() { return tags; }
     public void setTags(List<String> tags) { this.tags = tags; }

     public List<LineItem> getLineItems() { return lineItems; }
     public void setLineItems(List<LineItem> lineItems) { this.lineItems = lineItems; }

     public List<Object> getNotifications() { return notifications; }
     public void setNotifications(List<Object> notifications) { this.notifications = notifications; }

     public List<Object> getMixedShapeArray() { return mixedShapeArray; }
     public void setMixedShapeArray(List<Object> mixedShapeArray) { this.mixedShapeArray = mixedShapeArray; }

     public String getFirstName() { return firstName; }
     public void setFirstName(String firstName) { this.firstName = firstName; }

     public String getLastName() { return lastName; }
     public void setLastName(String lastName) { this.lastName = lastName; }

    public static class ShippingAddress {
         private String street;
         private String city;
         private String zip;

         public String getStreet() { return street; }
         public void setStreet(String street) { this.street = street; }

         public String getCity() { return city; }
         public void setCity(String city) { this.city = city; }

         public String getZip() { return zip; }
         public void setZip(String zip) { this.zip = zip; }
    }

    public static class LineItem {
         private String sku;
         private int quantity;
         private double unitPrice;

         public String getSku() { return sku; }
         public void setSku(String sku) { this.sku = sku; }

         public int getQuantity() { return quantity; }
         public void setQuantity(int quantity) { this.quantity = quantity; }

         public double getUnitPrice() { return unitPrice; }
         public void setUnitPrice(double unitPrice) { this.unitPrice = unitPrice; }
    }
}
