package dev.gaphunter.jsontocodecompanion.generate

import dev.gaphunter.jsontocodecompanion.model.FieldSpec
import dev.gaphunter.jsontocodecompanion.model.InferredType

/**
 * Pure string rendering, no PSI mutation -- same separation already
 * proven in this catalog between "what should the text look like" and
 * "is it safe to write" (see Bean Copy Companion's `CopierWriter`/
 * `InMemoryValidator` split).
 *
 * A field whose type is [InferredType.Unknown] (from a JSON `null`, or
 * an empty/mixed-shape array) is rendered as `Object`/`Any` with a
 * trailing `// TODO(json-to-code): ...` comment -- never a guessed
 * type. A JSON key that needed sanitizing into a valid identifier gets
 * its original key preserved in a comment too.
 */
object CodeRenderer {

    fun renderJava(root: InferredType.ObjectType, packageName: String?): String {
        val classes = ClassCollector.collect(root)
        return buildString {
            if (!packageName.isNullOrEmpty()) {
                appendLine("package $packageName;")
                appendLine()
            }
            appendLine("import java.util.List;")
            appendLine()
            appendLine("/**")
            appendLine(" * Generated by JSON to Code Companion from a JSON sample.")
            appendLine(" * Do not hand-edit; regenerate instead.")
            appendLine(" */")
            appendLine("public class ${classes.first().className} {")
            appendJavaClassBody(this, classes.first(), "    ")
            for (nested in classes.drop(1)) {
                appendLine()
                appendLine("    public static class ${nested.className} {")
                appendJavaClassBody(this, nested, "        ")
                appendLine("    }")
            }
            appendLine("}")
        }
    }

    private fun appendJavaClassBody(sb: StringBuilder, cls: InferredType.ObjectType, indent: String) {
        for (field in cls.fields) {
            val typeText = javaTypeText(field.type, boxed = false)
            val comment = fieldComment(field)
            sb.appendLine("$indent private $typeText ${field.safeName};$comment")
        }
        for (field in cls.fields) {
            val typeText = javaTypeText(field.type, boxed = false)
            val capitalized = field.safeName.replaceFirstChar { it.uppercaseChar() }
            sb.appendLine()
            sb.appendLine("$indent public $typeText get$capitalized() { return ${field.safeName}; }")
            sb.appendLine("$indent public void set$capitalized($typeText ${field.safeName}) { this.${field.safeName} = ${field.safeName}; }")
        }
    }

    private fun javaTypeText(type: InferredType, boxed: Boolean): String = when (type) {
        InferredType.StringType -> "String"
        InferredType.IntType -> if (boxed) "Integer" else "int"
        InferredType.LongType -> if (boxed) "Long" else "long"
        InferredType.DoubleType -> if (boxed) "Double" else "double"
        InferredType.BooleanType -> if (boxed) "Boolean" else "boolean"
        InferredType.Unknown -> "Object"
        is InferredType.ListType -> "List<${javaTypeText(type.elementType, boxed = true)}>"
        is InferredType.ObjectType -> type.className
    }

    fun renderKotlin(root: InferredType.ObjectType, packageName: String?): String {
        val classes = ClassCollector.collect(root)
        return buildString {
            if (!packageName.isNullOrEmpty()) {
                appendLine("package $packageName")
                appendLine()
            }
            appendLine("/**")
            appendLine(" * Generated by JSON to Code Companion from a JSON sample.")
            appendLine(" * Do not hand-edit; regenerate instead.")
            appendLine(" */")
            for ((index, cls) in classes.withIndex()) {
                if (index > 0) appendLine()
                appendLine("data class ${cls.className}(")
                for ((fieldIndex, field) in cls.fields.withIndex()) {
                    val typeText = kotlinTypeText(field.type)
                    val comment = fieldComment(field)
                    val comma = if (fieldIndex == cls.fields.lastIndex) "" else ","
                    appendLine("    val ${field.safeName}: $typeText$comma$comment")
                }
                appendLine(")")
            }
        }
    }

    private fun kotlinTypeText(type: InferredType): String = when (type) {
        InferredType.StringType -> "String"
        InferredType.IntType -> "Int"
        InferredType.LongType -> "Long"
        InferredType.DoubleType -> "Double"
        InferredType.BooleanType -> "Boolean"
        InferredType.Unknown -> "Any"
        is InferredType.ListType -> "List<${kotlinTypeText(type.elementType)}>"
        is InferredType.ObjectType -> type.className
    }

    private fun fieldComment(field: FieldSpec): String {
        val parts = mutableListOf<String>()
        if (field.originalKey != field.safeName) parts += "JSON key: \"${field.originalKey}\""
        if (typeIsOrContainsUnknown(field.type)) parts += "TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)"
        return if (parts.isEmpty()) "" else " // " + parts.joinToString(" -- ")
    }

    private fun typeIsOrContainsUnknown(type: InferredType): Boolean = when (type) {
        InferredType.Unknown -> true
        is InferredType.ListType -> type.elementType == InferredType.Unknown
        else -> false
    }
}
