/**
 * Generated by JSON to Code Companion from a JSON sample.
 * Do not hand-edit; regenerate instead.
 */
data class Order(
    val orderId: String,
    val customerId: Int,
    val totalCents: Long,
    val totalAmount: Double,
    val isPaid: Boolean,
    val couponCode: Any, // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
    val shippingAddress: ShippingAddress,
    val tags: List<String>,
    val lineItems: List<LineItem>,
    val notifications: List<Any>, // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
    val mixedShapeArray: List<Any>, // TODO(json-to-code): could not infer a specific type here (null value, or empty/mixed-shape array)
    val firstName: String,
    val lastName: String
)

data class ShippingAddress(
    val street: String,
    val city: String,
    val zip: String
)

data class LineItem(
    val sku: String,
    val quantity: Int,
    val unitPrice: Double
)
